### ISSUE TITLE
The Exception doesn't explicitly complain that 'crc32c' package is missing

### ISSUE THREAD

**Issue by Oni** [icgood/proxy-protocol#55]
This Exceptions is reached only when the 'crc32c' package is missing.

https://github.com/icgood/proxy-protocol/blob/4b9fec7747e02ba0564900b844236b4320f50024/proxyprotocol/tlv.py#L209

I think that the Exception should mention that.

**Comment by icgood** [comment]
Oof, this was very much unintended. I was shadowing the name `crc32c` as both a TLV value and the function that computes it, resulting in some bad checks.

Fixed in 0.11.2.
